

###
# get list of users
GET http://localhost:3001/api/users

###
# create a user test
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username":"second@test.com",
    "name":"Lisa C",
    "password":"secret"
}

### 
# login user
POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
    "username":"second@test.com",
    "password":"secret"
}

###
# getting blogs made by the user
GET http://localhost:3001/api/blogs HTTP/1.1

###
# create a post as a specific user
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNlY29uZEB0ZXN0LmNvbSIsImlkIjoyLCJpYXQiOjE3NzI2NzI2MzR9.WviG-hglrqq1NlafNeNx7nrQPhH2KKINX__fp5aUJn4

{
    "title":"Awesome Story 2",
    "author":"Lisa C",
    "url":"www.lisa_c.dev/blog",
    "likes":300
}

###
# test wrong bearer token
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NkpXVCJ9.eyJ1c2VybmFtZSI6IlRlc3RAdGVzdC5jb20iLCJpZCI6MSwiaWF0IjoxNzcyNjU2NjczfQ.loUpU-6MNsEWF8mviwqhJBdX8-8-8d2oXhJ2fZIxrV4

{
    "title":"My Blog",
    "author":"Luke C",
    "url":"www.lukec.dev/blog",
    "likes":10000 
}