

###
# get list of users
GET http://localhost:3001/api/users

###
# create a user test
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username":"Luke Test",
    "name":"Luke C",
    "password":"secret"
}
