# Get request test
GET http://localhost:3001/api/blogs

###

# Post request test
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
    "author": "Luke C",
    "url":"www.github.com",
    "title":"I like github",
    "likes": 0,
    "date": null
}

###
# Post request test error handler
POST http://localhost:3001/api/blogs HTTP/1.1
content-type: application/json

{
    "author": "Luke C",
    "likes": 0,
    "date": null
}

###
# Delete test
DELETE http://localhost:3001/api/blogs/4

###
# Update test
PUT http://localhost:3001/api/blogs/1 HTTP/1.1
content-type: application/json

{
    "author": "Luke C",
    "url":"www.github.com",
    "title":"I like github",
    "likes": 1012,
    "date": null
}