# Get request test
GET http://localhost:3001/api/notes

###

# Post request test
POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json

{
    "content": "Another note for Luke",
    "important": false
}

###

GET http://localhost:3001/api/notes/1

###
# Creating a user
POST http://localhost:3001/api/users HTTP/1.1
content-type: application/json

{
    "username": "Pope-w",
    "name": "Pope W"
}

###
# Getting all users
GET http://localhost:3001/api/users


###
# Login blocking test

POST http://localhost:3001/api/login HTTP/1.1
content-type: application/json

{
    "username": "Pope-w",
    "password": "secret"
}